# ==========================
# RANGER RC.CONF (Kanagawa)
# ==========================

# General
set preview_files true
set show_hidden true
set draw_borders true
set preview_images true
set preview_images_method kitty

# Sorting
set sort natural
set sort_reverse false
set show_hidden true
set draw_borders true

# Colorscheme
set colorscheme kanagawa

# UI tweaks
set column_ratios 1,2,3
set confirm_on_delete true

# Misc
map zh toggle_show_hidden
map zr toggle_sort_reverse
map zs toggle_sort

